name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Clone the external repo
        run: git clone https://github.com/awslabs/aws-support-tools.git
      - run: echo AWS repository has been cloned to the runner."
      - name: Navigate to the cloned repo
        run: cd aws-support-tools
      - name: Execute the script
        run: python3 aws-support-tools/MWAA/verify_env/verify_env.py --envname test --region us-east-1
      - run: echo "🍏 This job's status is ${{ job.status }}."
